name: Debug Shell via Tmate
on:
  workflow_dispatch:  # Allows you to trigger the workflow manually
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Start Tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Keep session alive
        run: sleep 3600  # Keeps the session open for 1 hour
